#!/usr/bin/env python3

import sys
import random

if len(sys.argv)<3:
    print("USAGE: ....",file=sys.stderr)
    sys.exit(1)

gmax=int(sys.argv[1])
nmax=int(sys.argv[2])
mmax=int(sys.argv[3])

ges=[]
for _ in range(gmax):
    lotto=set()
    while len(lotto)<6:
        lotto.add(random.randint(1,mmax))
    ges.append(lotto)

"""
for (n,lotto) in enumerate(ges,1):
    print(n,":",end="")
    for z in lotto:
        print(z,"",end="")
    print()
"""

stat={}
for i in range(mmax+1): stat[i]=0

for lotto in ges:
    for z in lotto: stat[z]+=1

sortedStat=sorted(stat.items(),key=lambda x:x[1])
print( sortedStat[-6:])


"""
sep=4
for n in range(1,mmax+1):
     print(n,"-->",stat[n],"",end="")
     sep+=1
     if sep%4==0:
         print()
         sep=1
print()
"""

