#!/usr/bin/env python3

class Person(object):

    def __init__( self):
        self.name=""
        self.ort=""

    def ausgeben(self):
        print()

if __name__ == "__main__":
    
    p=Person()
    p.name="bauer"
    p.ausgeben()

