#!/usr/bin/env python3

import sys

filename=sys.argv[1]

wordlist={}
for line in open(filename):
    for word in line.split():
       if not word in wordlist: 
           wordlist[word]=0
       wordlist[word]+=1

for (k,v) in sorted(wordlist.items(),key=lambda x:-x[1])[:6]:
   print( k,"-->",v)


